version: '3.8'
services:
  stt-service:
    build: ./stt-service
    runtime: nvidia
    ports:
      - "5085:5085"
    environment:
      - MODEL_PATH=/models/islomov_navaistt_v2_medium_ct2
      - NVIDIA_VISIBLE_DEVICES=0
      - API_TOKEN=${API_TOKEN}
    # <<< УДАЛЕНО секцию healthcheck

  webui-service:
    build: ./webui-service
    ports:
      - "7860:7860"
    environment:
      - STT_API=http://stt-service:5085/transcribe
      - API_TOKEN=${API_TOKEN}
      - UI_USER=${UI_LOGIN}
      - UI_PASS=${UI_PASS}
    depends_on:
      - stt-service   # простая зависимость, без проверки здоровья
