version: '3.8'
services:
  stt-service:
    build: ./stt-service
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    ports:
      - "5085:5085"

  stt-webui:
    build: ./webui-service
    ports:
      - "7860:7860"
    environment:
      - STT_API=http://stt-service:5085/transcribe
    depends_on:
      - stt-service
