version: '3.8'
services:
  stt-service:
    build: ./stt-service
    runtime: nvidia
    ports:
      - "5085:5085"
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    # <<< УДАЛЕНО секцию healthcheck

  webui-service:
    build: ./webui-service
    ports:
      - "7860:7860"
    environment:
      - STT_API=http://stt-service:5085/transcribe
    depends_on:
      - stt-service   # простая зависимость, без проверки здоровья
